name: CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  lint-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint -- --max-warnings 0

  deploy-preview:
    runs-on: ubuntu-latest
    needs: [lint-check]
    if: github.event_name == 'pull_request'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Verify build output
        run: |
          echo "🔍 Verifying build output..."
          if [ ! -d ".next" ]; then
            echo "❌ Build failed: .next directory not found"
            exit 1
          fi

          if [ ! -f ".next/BUILD_ID" ]; then
            echo "❌ Build failed: BUILD_ID file not found"
            exit 1
          fi

          if [ ! -d ".next/static" ]; then
            echo "❌ Build failed: static directory not found"
            exit 1
          fi

          echo "✅ Build verification successful!"
          echo "Build ID: $(cat .next/BUILD_ID)"

      - name: Build successful
        run: echo "✅ Lint checks passed! Build verified successfully!"

  deploy-production:
    runs-on: ubuntu-latest
    needs: [lint-check]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Verify build output
        run: |
          echo "🔍 Verifying build output..."
          if [ ! -d ".next" ]; then
            echo "❌ Build failed: .next directory not found"
            exit 1
          fi

          if [ ! -f ".next/BUILD_ID" ]; then
            echo "❌ Build failed: BUILD_ID file not found"
            exit 1
          fi

          if [ ! -d ".next/static" ]; then
            echo "❌ Build failed: static directory not found"
            exit 1
          fi

          echo "✅ Build verification successful!"
          echo "Build ID: $(cat .next/BUILD_ID)"

      - name: Deploy to production
        run: |
          echo "🚀 Deploying to production..."
          echo "✅ All checks passed! Build verified successfully!"
          # Add your deployment commands here
          # Examples:
          # - Deploy to Vercel: vercel --prod
          # - Deploy to Netlify: netlify deploy --prod
          # - Deploy to AWS: aws s3 sync .next/static s3://your-bucket
